apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: serve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: model
        image: model:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
